### ISSUE TITLE
Propkill bypass

### ISSUE THREAD

**Issue by Matters401** [urnotnick/impulse-issues#227]
**Describe the bug**
It has been observed that individuals possess the ability to circumvent the prop kill safeguard mechanism and employ sittable chairs as projectiles towards others, particularly if an individual happens to be occupying the said chair.

**To reproduce**
Steps to reproduce the behaviour:
1. Spawn a vehicle chair
2. Get a friend to sit in that chair
3. Ensure you have a fast (phsygun_wheelspeed) for propkilling
4. Throw chair at player

**Expected behaviour**
The chair is meant to glow red, indicating it's safeguard and ghosting to prevent propkill.

**Screenshots**
N/A

**impulse version (press F1 in the bottom right):**
1.12.0

**Lua error**
N/A

**Additional context**

**Comment by SpriteCran** [comment]
Hi there.

This isn't necessarily an issue, as props and chairs are functionally (and visibly) different, and the rules have accompanying distinctions between props and chairs. While you would normally be right in the sense that it is supposed to turn red and become non-collided to symbolize being "ghosted", chairs don't follow this rule because they are "vehicles". This also has to do with a few things on how Falco's Prop Protection works, as this isn't a coded feature in the schema nor the framework, rather in the FPP addon. Or so last I checked.

Consequently, because the ability to do so is present, we have restrictions on ability to do so flat out, with violators being banned like any other major rule-break, or in some cases, even resulting in them being stripped of their donator privileges.

-Sprite

**Comment by justinbrick** [comment]
This is also something that only donators can do - we work on the honors system in this case, and people are punished accordingly.
