### ISSUE TITLE
Ration bypassing inventory limit

### ISSUE THREAD

**Issue by Locke206** [urnotnick/impulse-issues#59]
**Describe the bug**
When you get your ration and you have a full inventory your ration will still enter your inventory, making it heavier than the limit.
**To reproduce**
Steps to reproduce the behaviour:
1. Fill your inventory
2. Go to RDC
3. Get your ration

**Expected behaviour**
You will get your ration and will have an overflowing inventory e.g. 21kg/20kg

**Screenshots**

https://user-images.githubusercontent.com/104390937/165162083-c4b6f15c-0ee3-4141-8a4c-1702d08b9598.jpg

**impulse version (press F1 in the bottom right):**
1.10.3

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by X-Mezo-X** [comment]
I've noticed that Issue, but it's simply similar to the equipment of combine that you get , leading you to go past the weight limit, it doesn't really give you much advantage basically, and it's not gonna make much difference if it stays that way, because previously with rations, you got hunger and credits right away, so i don't feel it'll make much difference to keep it that way, especially when it doesn't give you any form of advantage.

**Comment by Astrroo** [comment]
Not an issue.
